### ISSUE TITLE
Allow custom branch prefix

### ISSUE THREAD

**Issue by keltonpsilva** [lablnet/create-branch-from-tag#2]
**Is your feature request related to a problem? Please describe.**
By default we are creating `release@{tagName}`, but if you allow the user to insert a custom prefix would make it easier to integrate with their git branches strategy.

**Describe the solution you'd like**

``` 
brach_prefix: string
required: false
```

**Describe alternatives you've considered**

**Additional context**

**Comment by lablnet** [comment]
Thanks for opening issue and providing solution.
