### ISSUE TITLE
Warnings in actions log

### ISSUE THREAD

**Issue by eliasbalasis** [lablnet/create-branch-from-tag#5]
**Describe the bug**
Warnings are displayed in actions log

**To Reproduce**
Run the action and observe the log

**Expected behavior**
No errors or warnings

**Screenshots**
![image](https://github.com/lablnet/create-branch-from-tag/assets/1681838/31154fa2-f450-4e4c-b10c-e0e7cd4249d7)

**Desktop (please complete the following information):**
Not applicable

**Smartphone (please complete the following information):**
Not applicable

**Additional context**

**Comment by lablnet** [comment]
Thanks for your report. Fixed in `v1.0.2`

Now you should use `v1.0.2`

```yaml            
- name: Create a Branch
  uses: lablnet/create-branch-from-tag@v1.0.2
```
