### ISSUE TITLE
Warnings in actions log at 1.0.4

### ISSUE THREAD

**Issue by eliasbalasis** [lablnet/create-branch-from-tag#7]
**Describe the bug**
Warnings are displayed in actions log

**To Reproduce**
Run the action and observe the log

**Expected behavior**
No errors or warnings

**Screenshots**
![image](https://github.com/lablnet/create-branch-from-tag/assets/1681838/c00aa1d1-46c2-428a-ae61-7f07da53a781)

**Desktop (please complete the following information):**
Not applicable

**Smartphone (please complete the following information):**
Not applicable

**Additional context**

**Comment by lablnet** [comment]
Which version you're using?

**Comment by eliasbalasis** [comment]
The one in the title
1.0.4

**Comment by lablnet** [comment]
Please use latest version of `checkout` action it will solve your issue
